version: "3.8"

networks:
    web:

services:
    #NGINX
    nginx:
        image: nginx:stable-alpine
        container_name: boilerplate_nginx
        ports:
            - "${HOST_NGINX_PORT:-80}:80"
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - database
            - redis
        networks:
            - web
    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: boilerplate_php
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        ports:
            - "${HOST_PHP_PORT:-9000}:9000"
        environment:
            - COMPOSER_MEMORY_LIMIT=-1
        networks:
            - web
        depends_on:
            - database
            - redis

    #Database Server
    database:
        image: mysql:8.0
        container_name: boilerplate_mysql
        ports:
            - "${HOST_MYSQL_PORT:-3306}:3306"
        environment:
            -   MYSQL_DATABASE=${DB_DATABASE}
            -   MYSQL_USER=${DB_USERNAME}
            -   MYSQL_PASSWORD=${DB_PASSWORD}
            -   MYSQL_ROOT_PASSWORD=rootpassword
            -   SERVICE_NAME=mysql
        volumes:
            -   db-data:/var/lib/mysql
        networks:
            - web


    #Redis Server
    redis:
        image: redis:alpine
        container_name: boilerplate_redis
        command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
        ports:
            - "${HOST_REDIS_PORT:-6379}:6379"
        networks:
            - web

volumes:
    db-data: ~
